[2017-05-11 13:56:19,072: ERROR/MainProcess] consumer: Cannot connect to redis://139.224.232.97:6379/5: .
Trying again in 2.00 seconds...

[2017-05-11 13:56:21,092: ERROR/MainProcess] consumer: Cannot connect to redis://139.224.232.97:6379/5: .
Trying again in 4.00 seconds...

[2017-05-11 13:56:25,113: ERROR/MainProcess] consumer: Cannot connect to redis://139.224.232.97:6379/5: .
Trying again in 6.00 seconds...

[2017-05-11 13:56:31,137: ERROR/MainProcess] consumer: Cannot connect to redis://139.224.232.97:6379/5: .
Trying again in 8.00 seconds...

[2017-05-11 13:56:39,160: ERROR/MainProcess] consumer: Cannot connect to redis://139.224.232.97:6379/5: .
Trying again in 10.00 seconds...

[2017-05-11 13:56:44,407: INFO/MainProcess] Connected to redis://127.0.0.1:6379/5
[2017-05-11 13:56:44,417: INFO/MainProcess] mingle: searching for neighbors
[2017-05-11 13:56:45,424: INFO/MainProcess] mingle: all alone
[2017-05-11 13:56:45,443: WARNING/MainProcess] celery@LAPTOP-EIDRP1PN ready.
[2017-05-11 13:58:48,023: INFO/MainProcess] Received task: tasks.login.login_task[a23f43b7-c15b-405b-b95c-c0f168e6114b]
[2017-05-11 13:58:48,785: ERROR/Worker-1] ±¾´ÎÕËºÅ13260956760µÇÂ½Ê§°Ü
[2017-05-11 13:58:48,788: INFO/MainProcess] Task tasks.login.login_task[a23f43b7-c15b-405b-b95c-c0f168e6114b] succeeded in 0.7659999999996217s: None
